#!/user/bin/env bash

#Bash completion for notes app

if ! command -v note &> /dev/null; then
    return
fi

_note(){
    COMPREPLY=($(compgen -W "add create edit list read remove rename" "${COMP_WORDS[1]}"))
}


complete -F _note note